layout:
    actions:
        - '@addTree':
            items:
                app_product_view_media_container:
                    blockType: layout_subtree_update
                    options:
                        reloadEvents: [ 'layout-subtree:update:product' ]
            tree:
                product_view_aside_container:
                    app_product_view_media_container: ~
        - '@setOption':
            id: product_view_attribute_group_images
            optionName: entity
            optionValue: '=data["oro_product_variant"].getProductVariantOrProduct(data)'
        - '@move':
            id: product_view_media_container
            parentId: app_product_view_media_container


